default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("SQL_USER") %>
  password: <%= ENV.fetch("SQL_KEY") %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: tweet_picker_development

test:
  <<: *default
  database: tweet_picker_test

production:
  <<: *default
  database: tweet_picker_production
  username: tweet_picker
  password: <%= ENV['TWEET_PICKER_DATABASE_PASSWORD'] %>
